### ISSUE TITLE
This variant doesn't work for me

### ISSUE THREAD

**Issue by 5T33Z0** [TheHackGuy/Codec-Graph#2]
Hi,

while workin on my [Guide](https://github.com/5T33Z0/OC-Little-Translated/tree/main/L_ALC_Layout-ID) for creating ALC Layout-IDs, I noticed your variant of Codecgraph supports Python 3 for macOS Monterey compatibility.

I tested your version in Catalina in python 3, trying to convert my Codec Dump, but it fails. The original version runs fine though.

Attached you find my Codec dump. Maybe you can test if it works for: [codec_dump.txt.zip](https://github.com/cmatsuoka/codecgraph/files/8805519/codec_dump.txt.zip)

If it does work, please tell me what I am doing wrong. Thank you.

**Comment by Core-i99** [comment]
I personally tested this on Monterey I think.
This evening I'll give it a try with a Mojave vm, I currently don't have a Catalina one.

Nice that you're writing a guide!

**Comment by Core-i99** [comment]
@5T33Z0 Your codec dump successfully converted on Monterey 12.4. (results attached)
I'll test it on Mojave later this evening.
[output.zip](https://github.com/Core-i99/Codec-Graph/files/8806358/output.zip)

In the mean time: Can you maybe make a video  of what happens when you run this tool?

**Comment by 5T33Z0** [comment]
Okay, thanks. 

Since I a am not a dev, can you tell me the terminal commands you used, before I make a video?

The version I have also includes an executable of codecgrapher and 2 additional scripts: [verbit.sh ](https://github.com/armenio/verbit.sh/blob/master/verbit.sh) and this [script](https://github.com/nguyenngocanh94/AppleHDA/blob/master/codecgraph/Scrip%20Patch%20Codec%20by%20HoangThanh). 

I only have to double-click on the 2nd one and everything else  works automatically. Maybe I have to adjust that for pyhon 3 as well?

**Comment by Core-i99** [comment]
cd into codec graph directory
Then python3 Codec-Graph.py

Also, I do have a separate branch which has a gui, I'm planning to let my github runner build an macOS app from it.

**Comment by 5T33Z0** [comment]
Wow, an app would be awesome! There are almost no apps available for AppleALC stuff so this would be cool.

Another thing: Do you have an idea why the arrows inside the visualizations all point to the right? I don't know why that is but they definitely do not represent signal flow. Do you think there's a way to make it use lines instead? I guess this is a graphviz setting?

**Comment by Core-i99** [comment]
No idea on these arrows, I'm not that familiar with graphviz. 
Do you have discord or anything like that? Would be much easier and faster than these github comments...
My discord: Core i99#7633

**Comment by 5T33Z0** [comment]
I have an account. I don't quite how discord works, but I try adding you.

**Comment by Core-i99** [comment]
The issue was the terminal background being black, while the text the script prints is also black. So you wouldn't see anything.
I'm going to work on a GUI for Codec Graph later, once I finish this I'll close the issue.
